spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.20.216.221:3306/arthur
server:
  port: 8966
word:
    fst: "fst"
    sec: "sec"

